name: CMake Build, Test, Package, Docs, Lint and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen clang-format cppcheck lcov

    - name: Lint Code with Clang-Format
      run: clang-format --dry-run --Werror include/*.hpp sources/*.cpp examples/*.cpp tests/*.cpp

    - name: Static Analysis with Cppcheck
      run: cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --suppress=unusedFunction include/ sources/

    - name: Configure CMake
      run: cmake -B build -S . -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON

    - name: Build project
      run: cmake --build build

    - name: Run Tests
      run: cd build && ctest --output-on-failure

    - name: Generate Coverage Report
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*third-party*' '*tests*' --output-file filtered_coverage.info
        genhtml filtered_coverage.info --output-directory coverage_report

    - name: Create Packages via CPack
      run: cd build && cpack

    - name: Generate Documentation via Doxygen
      run: doxygen Doxyfile

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: project-artifacts-and-coverage
        path: |
          build/*.tar.gz
          build/*.deb
          docs/html/
          coverage_report/
